# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tcOops website
email: 1991tanc@gmail.com
description: Source of me
baseurl:  /hololens# the subpath of your site, e.g. /blog
urls: http://localhost:4000 # the base hostname & protocol for your site
url: www.spacenx.pw/hololens
twitter_username: 
github_username:  tcOops
github: https://github.com/tcOops?tab=repositories
weixin_username: tcOops

# Build settings
markdown: rdiscount

